"""
--- Day 9: Rope Bridge ---
This rope bridge creaks as you walk along it. You aren't sure how old it is, or
whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which
was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to
distract yourself by modeling rope physics; maybe you can even figure out where
not to step.

Consider a rope with a knot at each end; these knots mark the head and the tail
of the rope. If the head moves far enough away from the tail, the tail is pulled
toward the head.

Due to nebulous reasoning involving Planck lengths, you should be able to model
the positions of the knots on a two-dimensional grid. Then, by following a
hypothetical series of motions (your puzzle input) for the head, you can
determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact,
the head (H) and tail (T) must always be touching (diagonally adjacent and even
overlapping both count as touching):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...
If the head is ever two steps directly up, down, left, or right from the tail,
the tail must also move one step in that direction so it remains close enough:

.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...
Otherwise, if the head and tail aren't touching and aren't in the same row or
column, the tail always moves one step diagonally to keep up:

.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....
You just need to work out where the tail goes as the head follows a series of
motions. Assume the head and the tail both start at the same position,
overlapping.

For example:

R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2
This series of motions moves the head right four steps, then up four steps, then
left three steps, then down one step, and so on. After each step, you'll need to
update the position of the tail if the step means the head is no longer adjacent
to the tail. Visually, these motions occur as follows (s marks the starting
position as a reference point):

== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....
After simulating the rope, you can count up all of the positions the tail
visited at least once. In this diagram, s again marks the starting position
(which the tail also visited) and # marks other positions the tail visited:

..##..
...##.
.####.
....#.
s###..
So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions. How many positions does
the tail of the rope visit at least once?
"""

import sys


class Position(object):
    def __init__(self, x, y, is_tail=False):
        self.x = x
        self.y = y
        if is_tail:
            self.tail_positions = set()
            self.missing_cases = set()
        else:
            self.tail_positions = None

    def up(self):
        self.y += 1

    def down(self):
        self.y -= 1

    def left(self):
        self.x -= 1

    def right(self):
        self.x += 1

    def distance(self, other):
        x_dist = other.x - self.x
        y_dist = other.y - self.y
        if abs(x_dist) > 2 or abs(y_dist) > 2:
            pass
        return x_dist, y_dist

    def adjust(self, other):
        x_dist, y_dist = self.distance(other)
        if abs(x_dist) + abs(y_dist) == 3:
            # These all require two moves.
            if x_dist > 0:
                self.right()
            else:
                self.left()
            if y_dist > 0:
                self.up()
            else:
                self.down()
        else:
            if x_dist == 2:
                self.right()
            elif x_dist == -2:
                self.left()
            if y_dist == 2:
                self.up()
            elif y_dist == -2:
                self.down()
        # If adjust is called on the  head, this will raise an exception.
        # That's a feature, since we only want to adjust the tail to
        # match the head.
        self.tail_positions.add((self.x, self.y))

    def output_how_many_tail_positions(self):
        print(len(self.tail_positions))


def main():
    if len(sys.argv) > 1 and sys.argv[1] == 'test':
        input_file = open('9test.txt')
    else:
        input_file = open('9input.txt')
    head = Position(0, 0)
    tail = Position(0, 0, is_tail=True)
    steps = [x.split(' ') for x in input_file.read().split('\n')]
    for step in steps:
        if step[0] == 'R':
            for n in range(int(step[1])):
                head.right()
                tail.adjust(head)
        elif step[0] == 'L':
            for n in range(int(step[1])):
                head.left()
                tail.adjust(head)
        elif step[0] == 'U':
            for n in range(int(step[1])):
                head.up()
                tail.adjust(head)
        elif step[0] == 'D':
            for n in range(int(step[1])):
                head.down()
                tail.adjust(head)
        else:
            raise Exception("Can't get here!")
    tail.output_how_many_tail_positions()


if __name__ == '__main__':
    main()
